/// Common English words ordered approximately by frequency.
/// The ordering is important for Zipf distribution - more frequent words come first.
pub const VOCABULARY: &[&str] = &[
    // Top 100 most common words
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
    "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
    // 100-200
    "very", "when", "need", "much", "right", "still", "child", "here", "where", "help",
    "through", "many", "before", "line", "same", "another", "live", "thing", "long", "world",
    "been", "tell", "great", "must", "part", "name", "write", "call", "high", "old",
    "number", "find", "feel", "each", "every", "own", "should", "home", "leave", "put",
    "hand", "again", "change", "off", "play", "never", "does", "point", "small", "end",
    "show", "ask", "start", "few", "too", "place", "keep", "head", "read", "let",
    "move", "try", "kind", "begin", "seem", "mean", "those", "group", "always", "while",
    "last", "might", "next", "own", "face", "fact", "case", "state", "turn", "such",
    "both", "being", "sure", "why", "may", "big", "little", "side", "word", "public",
    "school", "enough", "run", "different", "house", "set", "govern", "under", "city", "between",
    // 200-300
    "family", "company", "power", "country", "week", "area", "system", "program", "question", "during",
    "possible", "business", "without", "present", "problem", "three", "late", "develop", "room", "market",
    "hold", "issue", "against", "money", "person", "service", "member", "law", "open", "book",
    "example", "bring", "believe", "young", "body", "include", "month", "report", "life", "continue",
    "study", "course", "since", "until", "often", "around", "once", "however", "early", "nothing",
    "yet", "important", "able", "form", "local", "national", "political", "ever", "student", "human",
    "though", "really", "something", "general", "sit", "water", "night", "level", "force", "game",
    "everything", "above", "rather", "million", "second", "almost", "stand", "already", "away", "build",
    "best", "among", "war", "provide", "result", "idea", "social", "himself", "fall", "interest",
    "several", "stop", "economic", "rate", "minute", "either", "police", "office", "themselves", "least",
    // 300-400
    "perhaps", "story", "street", "car", "sense", "whole", "become", "happen", "together", "quite",
    "team", "less", "free", "talk", "woman", "control", "today", "lose", "pay", "behind",
    "community", "meet", "price", "cause", "better", "reason", "experience", "court", "hear", "record",
    "education", "hope", "period", "probably", "matter", "sometimes", "actually", "moment", "decision", "party",
    "action", "health", "news", "music", "ago", "major", "certain", "parent", "morning", "plan",
    "history", "land", "whether", "cut", "across", "view", "easy", "love", "process", "along",
    "father", "door", "center", "low", "information", "president", "mother", "security", "player", "age",
    "research", "white", "fund", "paper", "policy", "technology", "black", "support", "follow", "deal",
    "eye", "leader", "art", "death", "cost", "industry", "expect", "job", "table", "data",
    "half", "close", "director", "road", "especially", "understand", "carry", "return", "true", "window",
    // 400-500
    "voice", "role", "space", "special", "soon", "south", "toward", "hour", "near", "finally",
    "federal", "food", "evidence", "event", "clear", "hard", "management", "offer", "air", "region",
    "theory", "figure", "risk", "care", "north", "light", "serve", "personal", "future", "reach",
    "watch", "effect", "particular", "production", "staff", "performance", "remember", "board", "strong", "term",
    "investment", "common", "west", "east", "wrong", "tax", "computer", "image", "bank", "fire",
    "manager", "class", "account", "growth", "patient", "individual", "building", "wait", "product", "sign",
    "appear", "foot", "simply", "movie", "rule", "store", "value", "song", "attack", "ground",
    "analysis", "hair", "environment", "wall", "position", "field", "medical", "finally", "defense", "trade",
    "condition", "benefit", "foreign", "movie", "material", "amount", "son", "trial", "bad", "single",
    "practice", "sell", "situation", "model", "choice", "source", "attention", "break", "test", "anyone",
    // 500-600
    "visit", "worker", "author", "challenge", "activity", "star", "training", "central", "season", "natural",
    "structure", "station", "past", "campaign", "consider", "measure", "population", "usually", "election", "cell",
    "successful", "thought", "top", "step", "authority", "bit", "chance", "scene", "various", "approach",
    "base", "shot", "opportunity", "standard", "private", "quality", "reach", "street", "former", "color",
    "inside", "official", "treatment", "entire", "beat", "apply", "floor", "realize", "goal", "economy",
    "leader", "teacher", "financial", "cover", "blood", "resource", "culture", "series", "stage", "pull",
    "increase", "herself", "similar", "type", "arm", "address", "media", "travel", "bill", "stay",
    "design", "outside", "available", "knowledge", "focus", "professor", "drive", "consumer", "movie", "effort",
    "energy", "debate", "physical", "style", "recent", "strategy", "sport", "current", "drug", "marriage",
    "legal", "section", "weapon", "speech", "order", "property", "impact", "agency", "pressure", "project",
    // 600-700
    "smile", "accept", "brother", "sister", "dream", "laugh", "share", "friend", "animal", "college",
    "character", "crime", "deep", "wish", "note", "doctor", "bar", "husband", "operation", "network",
    "truth", "agreement", "responsibility", "nature", "plant", "feature", "fill", "assume", "machine", "film",
    "message", "sex", "statement", "ahead", "hit", "response", "huge", "forward", "capital", "hotel",
    "summer", "glass", "significant", "concern", "success", "generation", "oil", "baby", "organization", "hot",
    "language", "beautiful", "identify", "employee", "conference", "dead", "box", "subject", "democratic", "middle",
    "lack", "final", "interview", "peace", "miss", "vote", "fund", "tree", "race", "protect",
    "soldier", "sport", "movement", "enjoy", "total", "ball", "western", "save", "send", "decade",
    "method", "magazine", "release", "painting", "seat", "behavior", "collection", "suddenly", "finger", "detail",
    "myself", "page", "tradition", "prevent", "imagine", "join", "river", "stock", "push", "dinner",
    // 700-800
    "express", "feeling", "card", "avoid", "list", "bed", "red", "whatever", "represent", "mention",
    "establish", "prepare", "basic", "green", "mile", "blue", "complete", "victim", "season", "kitchen",
    "store", "throw", "allow", "argue", "science", "claim", "bit", "memory", "train", "suffer",
    "trouble", "degree", "reality", "corner", "target", "professional", "lay", "critical", "rock", "street",
    "associate", "demand", "fear", "garden", "trouble", "range", "ready", "church", "candidate", "shot",
    "produce", "lawyer", "regular", "win", "variety", "civil", "commercial", "agency", "charge", "remove",
    "battle", "pain", "artist", "century", "opinion", "responsibility", "animal", "traditional", "replace", "crowd",
    "weight", "judge", "remain", "instance", "popular", "claim", "unit", "pick", "pattern", "poor",
    "quickly", "original", "indeed", "gas", "skin", "reduce", "mostly", "rest", "front", "rain",
    "scientist", "hill", "hang", "southern", "brown", "shape", "firm", "key", "sign", "attend",
    // 800-900
    "perfect", "reform", "stone", "distance", "ticket", "contract", "credit", "surprise", "weather", "date",
    "potential", "wonderful", "maintain", "communication", "leg", "afternoon", "direct", "average", "correct", "park",
    "exchange", "vast", "link", "cancer", "observe", "safety", "neither", "connection", "famous", "spirit",
    "wood", "neck", "dress", "largely", "prison", "sleep", "fail", "fix", "boat", "emerge",
    "border", "struggle", "track", "limit", "seek", "brain", "destroy", "intellectual", "core", "relative",
    "supply", "speed", "principle", "chief", "actual", "spread", "tape", "executive", "aid", "favor",
    "whereas", "commission", "shape", "intend", "employee", "length", "annual", "presence", "participate", "grant",
    "bus", "version", "wine", "danger", "excellent", "lift", "vast", "domestic", "deny", "metal",
    "investigation", "speaker", "reference", "angry", "approve", "conflict", "compete", "index", "audience", "edge",
    "profit", "threat", "decline", "context", "capable", "primary", "alternative", "location", "sample", "emotional",
    // 900-1000
    "quarter", "occasion", "content", "obvious", "path", "settle", "finance", "internal", "crisis", "recommend",
    "phase", "touch", "revolution", "multiple", "household", "female", "male", "literature", "planet", "academic",
    "engine", "document", "bottle", "flower", "sheet", "chief", "technique", "vast", "budget", "software",
    "urban", "category", "normally", "client", "commitment", "initial", "acquire", "mental", "strike", "implement",
    "climate", "passenger", "slightly", "estimate", "score", "component", "recover", "shift", "transition", "spot",
    "colleague", "convention", "ultimately", "contribution", "citizen", "neighborhood", "channel", "fashion", "alliance", "wine",
    "display", "rural", "exception", "foundation", "resolve", "resistance", "assessment", "exposure", "proportion", "framework",
    "apparent", "distinction", "extensive", "regime", "proceed", "welfare", "inevitable", "contemporary", "expense", "tendency",
    "ministry", "moreover", "merely", "variable", "liberal", "notion", "facilitate", "criteria", "eliminate", "perception",
    "conclude", "generate", "comprehensive", "emerge", "abandon", "integrate", "dominant", "widespread", "ensure", "impose",
];
