use std::fmt;

#[derive(Debug, Clone)]
pub struct Keybinding {
    pub key: &'static str,
    pub description: &'static str,
    pub command: &'static str,
    pub mode: Mode,
    pub category: Category,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    Normal,
    Insert,
    Select,
    View,
    Goto,
    Match,
    Window,
    Space,
    Picker,
    Prompt,
    Unimpaired,
}

impl fmt::Display for Mode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Mode::Normal => write!(f, "Normal"),
            Mode::Insert => write!(f, "Insert"),
            Mode::Select => write!(f, "Select"),
            Mode::View => write!(f, "View (z/Z)"),
            Mode::Goto => write!(f, "Goto (g)"),
            Mode::Match => write!(f, "Match (m)"),
            Mode::Window => write!(f, "Window (Ctrl-w)"),
            Mode::Space => write!(f, "Space"),
            Mode::Picker => write!(f, "Picker"),
            Mode::Prompt => write!(f, "Prompt"),
            Mode::Unimpaired => write!(f, "Unimpaired ([/])"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    Movement,
    Changes,
    Selection,
    Search,
    Shell,
    MinorModes,
    Lsp,
    TreeSitter,
    Clipboard,
    Navigation,
    Editing,
    Window,
    Buffer,
    Other,
}

impl fmt::Display for Category {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Category::Movement => write!(f, "Movement"),
            Category::Changes => write!(f, "Changes"),
            Category::Selection => write!(f, "Selection"),
            Category::Search => write!(f, "Search"),
            Category::Shell => write!(f, "Shell"),
            Category::MinorModes => write!(f, "Minor Modes"),
            Category::Lsp => write!(f, "LSP"),
            Category::TreeSitter => write!(f, "Tree-sitter"),
            Category::Clipboard => write!(f, "Clipboard"),
            Category::Navigation => write!(f, "Navigation"),
            Category::Editing => write!(f, "Editing"),
            Category::Window => write!(f, "Window"),
            Category::Buffer => write!(f, "Buffer"),
            Category::Other => write!(f, "Other"),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Command {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub description: &'static str,
}

pub fn get_keybindings() -> Vec<Keybinding> {
    vec![
        // Normal Mode - Movement
        Keybinding { key: "h, Left", description: "Move left", command: "move_char_left", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "j, Down", description: "Move down", command: "move_visual_line_down", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "k, Up", description: "Move up", command: "move_visual_line_up", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "l, Right", description: "Move right", command: "move_char_right", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "w", description: "Move next word start", command: "move_next_word_start", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "b", description: "Move previous word start", command: "move_prev_word_start", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "e", description: "Move next word end", command: "move_next_word_end", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "W", description: "Move next WORD start", command: "move_next_long_word_start", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "B", description: "Move previous WORD start", command: "move_prev_long_word_start", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "E", description: "Move next WORD end", command: "move_next_long_word_end", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "t", description: "Find till next char", command: "find_till_char", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "f", description: "Find next char", command: "find_next_char", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "T", description: "Find till previous char", command: "till_prev_char", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "F", description: "Find previous char", command: "find_prev_char", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "<n>G, <n>gg", description: "Go to line number", command: "goto_line", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Alt-.", description: "Repeat last motion", command: "repeat_last_motion", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Home", description: "Move to line start", command: "goto_line_start", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "End", description: "Move to line end", command: "goto_line_end", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Ctrl-b, PageUp", description: "Move page up", command: "page_up", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Ctrl-f, PageDown", description: "Move page down", command: "page_down", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Ctrl-u", description: "Move half page up", command: "page_cursor_half_up", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Ctrl-d", description: "Move half page down", command: "page_cursor_half_down", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Ctrl-i", description: "Jump forward on jumplist", command: "jump_forward", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Ctrl-o", description: "Jump backward on jumplist", command: "jump_backward", mode: Mode::Normal, category: Category::Movement },
        Keybinding { key: "Ctrl-s", description: "Save selection to jumplist", command: "save_selection", mode: Mode::Normal, category: Category::Movement },

        // Normal Mode - Changes
        Keybinding { key: "r", description: "Replace with character", command: "replace", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "R", description: "Replace with yanked text", command: "replace_with_yanked", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "~", description: "Switch case", command: "switch_case", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "`", description: "Set to lowercase", command: "switch_to_lowercase", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Alt-`", description: "Set to uppercase", command: "switch_to_uppercase", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "i", description: "Insert before selection", command: "insert_mode", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "a", description: "Insert after selection (append)", command: "append_mode", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "I", description: "Insert at line start", command: "insert_at_line_start", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "A", description: "Insert at line end", command: "insert_at_line_end", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "o", description: "Open line below", command: "open_below", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "O", description: "Open line above", command: "open_above", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: ".", description: "Repeat last insert", command: "N/A", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "u", description: "Undo change", command: "undo", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "U", description: "Redo change", command: "redo", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Alt-u", description: "Move backward in history", command: "earlier", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Alt-U", description: "Move forward in history", command: "later", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "y", description: "Yank selection", command: "yank", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "p", description: "Paste after selection", command: "paste_after", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "P", description: "Paste before selection", command: "paste_before", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "\" <reg>", description: "Select register", command: "select_register", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: ">", description: "Indent selection", command: "indent", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "<", description: "Unindent selection", command: "unindent", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "=", description: "Format selection (LSP)", command: "format_selections", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "d", description: "Delete selection", command: "delete_selection", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Alt-d", description: "Delete without yanking", command: "delete_selection_noyank", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "c", description: "Change selection", command: "change_selection", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Alt-c", description: "Change without yanking", command: "change_selection_noyank", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Ctrl-a", description: "Increment number", command: "increment", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Ctrl-x", description: "Decrement number", command: "decrement", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "Q", description: "Start/stop macro recording", command: "record_macro", mode: Mode::Normal, category: Category::Changes },
        Keybinding { key: "q", description: "Play back macro", command: "replay_macro", mode: Mode::Normal, category: Category::Changes },

        // Normal Mode - Shell
        Keybinding { key: "|", description: "Pipe selection through shell", command: "shell_pipe", mode: Mode::Normal, category: Category::Shell },
        Keybinding { key: "Alt-|", description: "Pipe to shell, ignore output", command: "shell_pipe_to", mode: Mode::Normal, category: Category::Shell },
        Keybinding { key: "!", description: "Run shell, insert output before", command: "shell_insert_output", mode: Mode::Normal, category: Category::Shell },
        Keybinding { key: "Alt-!", description: "Run shell, append output after", command: "shell_append_output", mode: Mode::Normal, category: Category::Shell },
        Keybinding { key: "$", description: "Keep selections where cmd succeeds", command: "shell_keep_pipe", mode: Mode::Normal, category: Category::Shell },

        // Normal Mode - Selection
        Keybinding { key: "s", description: "Select regex matches in selection", command: "select_regex", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "S", description: "Split selection on regex", command: "split_selection", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-s", description: "Split selection on newlines", command: "split_selection_on_newline", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt--", description: "Merge selections", command: "merge_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-_", description: "Merge consecutive selections", command: "merge_consecutive_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "&", description: "Align selections in columns", command: "align_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "_", description: "Trim whitespace from selection", command: "trim_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: ";", description: "Collapse selection to cursor", command: "collapse_selection", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-;", description: "Flip selection cursor/anchor", command: "flip_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-:", description: "Ensure forward direction", command: "ensure_selections_forward", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: ",", description: "Keep only primary selection", command: "keep_primary_selection", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-,", description: "Remove primary selection", command: "remove_primary_selection", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "C", description: "Copy selection to next line", command: "copy_selection_on_next_line", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-C", description: "Copy selection to previous line", command: "copy_selection_on_prev_line", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "(", description: "Rotate selections backward", command: "rotate_selections_backward", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: ")", description: "Rotate selections forward", command: "rotate_selections_forward", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-(", description: "Rotate contents backward", command: "rotate_selection_contents_backward", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-)", description: "Rotate contents forward", command: "rotate_selection_contents_forward", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "%", description: "Select entire file", command: "select_all", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "x", description: "Select/extend current line", command: "extend_line_below", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "X", description: "Extend to line bounds", command: "extend_to_line_bounds", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-x", description: "Shrink to line bounds", command: "shrink_to_line_bounds", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "J", description: "Join lines in selection", command: "join_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-J", description: "Join lines with space", command: "join_selections_space", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "K", description: "Keep selections matching regex", command: "keep_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Alt-K", description: "Remove selections matching regex", command: "remove_selections", mode: Mode::Normal, category: Category::Selection },
        Keybinding { key: "Ctrl-c", description: "Toggle line comment", command: "toggle_comments", mode: Mode::Normal, category: Category::Selection },

        // Normal Mode - Tree-sitter
        Keybinding { key: "Alt-o, Alt-Up", description: "Expand selection to parent", command: "expand_selection", mode: Mode::Normal, category: Category::TreeSitter },
        Keybinding { key: "Alt-i, Alt-Down", description: "Shrink selection", command: "shrink_selection", mode: Mode::Normal, category: Category::TreeSitter },
        Keybinding { key: "Alt-p, Alt-Left", description: "Select previous sibling", command: "select_prev_sibling", mode: Mode::Normal, category: Category::TreeSitter },
        Keybinding { key: "Alt-n, Alt-Right", description: "Select next sibling", command: "select_next_sibling", mode: Mode::Normal, category: Category::TreeSitter },
        Keybinding { key: "Alt-a", description: "Select all siblings", command: "select_all_siblings", mode: Mode::Normal, category: Category::TreeSitter },
        Keybinding { key: "Alt-I, Alt-Shift-Down", description: "Select all children", command: "select_all_children", mode: Mode::Normal, category: Category::TreeSitter },
        Keybinding { key: "Alt-e", description: "Move to parent node end", command: "move_parent_node_end", mode: Mode::Normal, category: Category::TreeSitter },
        Keybinding { key: "Alt-b", description: "Move to parent node start", command: "move_parent_node_start", mode: Mode::Normal, category: Category::TreeSitter },

        // Normal Mode - Search
        Keybinding { key: "/", description: "Search regex pattern forward", command: "search", mode: Mode::Normal, category: Category::Search },
        Keybinding { key: "?", description: "Search regex pattern backward", command: "rsearch", mode: Mode::Normal, category: Category::Search },
        Keybinding { key: "n", description: "Select next search match", command: "search_next", mode: Mode::Normal, category: Category::Search },
        Keybinding { key: "N", description: "Select previous search match", command: "search_prev", mode: Mode::Normal, category: Category::Search },
        Keybinding { key: "*", description: "Search selection (word bounds)", command: "search_selection_detect_word_boundaries", mode: Mode::Normal, category: Category::Search },
        Keybinding { key: "Alt-*", description: "Search selection (no bounds)", command: "search_selection", mode: Mode::Normal, category: Category::Search },

        // Normal Mode - Minor Modes
        Keybinding { key: "v", description: "Enter select/extend mode", command: "select_mode", mode: Mode::Normal, category: Category::MinorModes },
        Keybinding { key: "g", description: "Enter goto mode", command: "N/A", mode: Mode::Normal, category: Category::MinorModes },
        Keybinding { key: "m", description: "Enter match mode", command: "N/A", mode: Mode::Normal, category: Category::MinorModes },
        Keybinding { key: ":", description: "Enter command mode", command: "command_mode", mode: Mode::Normal, category: Category::MinorModes },
        Keybinding { key: "z", description: "Enter view mode", command: "N/A", mode: Mode::Normal, category: Category::MinorModes },
        Keybinding { key: "Z", description: "Enter sticky view mode", command: "N/A", mode: Mode::Normal, category: Category::MinorModes },
        Keybinding { key: "Ctrl-w", description: "Enter window mode", command: "N/A", mode: Mode::Normal, category: Category::MinorModes },
        Keybinding { key: "Space", description: "Enter space mode", command: "N/A", mode: Mode::Normal, category: Category::MinorModes },

        // View Mode
        Keybinding { key: "z, c", description: "Center view vertically", command: "align_view_center", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "t", description: "Align view to top", command: "align_view_top", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "b", description: "Align view to bottom", command: "align_view_bottom", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "m", description: "Align view middle (horizontal)", command: "align_view_middle", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "j, Down", description: "Scroll down", command: "scroll_down", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "k, Up", description: "Scroll up", command: "scroll_up", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "Ctrl-f, PageDown", description: "Page down", command: "page_down", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "Ctrl-b, PageUp", description: "Page up", command: "page_up", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "Ctrl-u", description: "Half page up", command: "page_cursor_half_up", mode: Mode::View, category: Category::Navigation },
        Keybinding { key: "Ctrl-d", description: "Half page down", command: "page_cursor_half_down", mode: Mode::View, category: Category::Navigation },

        // Goto Mode
        Keybinding { key: "g", description: "Go to file start", command: "goto_file_start", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "<n>g", description: "Go to line n", command: "goto_file_start", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "|", description: "Go to line start / column", command: "goto_column", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "e", description: "Go to end of file", command: "goto_last_line", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "f", description: "Go to files in selections", command: "goto_file", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "h", description: "Go to line start", command: "goto_line_start", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "l", description: "Go to line end", command: "goto_line_end", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "s", description: "Go to first non-whitespace", command: "goto_first_nonwhitespace", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "t", description: "Go to window top", command: "goto_window_top", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "c", description: "Go to window center", command: "goto_window_center", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "b", description: "Go to window bottom", command: "goto_window_bottom", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "d", description: "Go to definition (LSP)", command: "goto_definition", mode: Mode::Goto, category: Category::Lsp },
        Keybinding { key: "y", description: "Go to type definition (LSP)", command: "goto_type_definition", mode: Mode::Goto, category: Category::Lsp },
        Keybinding { key: "r", description: "Go to references (LSP)", command: "goto_reference", mode: Mode::Goto, category: Category::Lsp },
        Keybinding { key: "i", description: "Go to implementation (LSP)", command: "goto_implementation", mode: Mode::Goto, category: Category::Lsp },
        Keybinding { key: "a", description: "Go to last accessed file", command: "goto_last_accessed_file", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "m", description: "Go to last modified file", command: "goto_last_modified_file", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "n", description: "Go to next buffer", command: "goto_next_buffer", mode: Mode::Goto, category: Category::Buffer },
        Keybinding { key: "p", description: "Go to previous buffer", command: "goto_previous_buffer", mode: Mode::Goto, category: Category::Buffer },
        Keybinding { key: ".", description: "Go to last modification", command: "goto_last_modification", mode: Mode::Goto, category: Category::Navigation },
        Keybinding { key: "j", description: "Move down textual line", command: "move_line_down", mode: Mode::Goto, category: Category::Movement },
        Keybinding { key: "k", description: "Move up textual line", command: "move_line_up", mode: Mode::Goto, category: Category::Movement },
        Keybinding { key: "w", description: "Go to word with labels", command: "goto_word", mode: Mode::Goto, category: Category::Navigation },

        // Match Mode
        Keybinding { key: "m", description: "Go to matching bracket", command: "match_brackets", mode: Mode::Match, category: Category::Navigation },
        Keybinding { key: "s <char>", description: "Surround selection with char", command: "surround_add", mode: Mode::Match, category: Category::Editing },
        Keybinding { key: "r <from><to>", description: "Replace surrounding chars", command: "surround_replace", mode: Mode::Match, category: Category::Editing },
        Keybinding { key: "d <char>", description: "Delete surrounding chars", command: "surround_delete", mode: Mode::Match, category: Category::Editing },
        Keybinding { key: "a <object>", description: "Select around textobject", command: "select_textobject_around", mode: Mode::Match, category: Category::Selection },
        Keybinding { key: "i <object>", description: "Select inside textobject", command: "select_textobject_inner", mode: Mode::Match, category: Category::Selection },

        // Window Mode
        Keybinding { key: "w, Ctrl-w", description: "Switch to next window", command: "rotate_view", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "v, Ctrl-v", description: "Vertical split (right)", command: "vsplit", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "s, Ctrl-s", description: "Horizontal split (below)", command: "hsplit", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "f", description: "Go to files (horizontal)", command: "goto_file", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "F", description: "Go to files (vertical)", command: "goto_file", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "h, Ctrl-h, Left", description: "Move to left split", command: "jump_view_left", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "j, Ctrl-j, Down", description: "Move to split below", command: "jump_view_down", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "k, Ctrl-k, Up", description: "Move to split above", command: "jump_view_up", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "l, Ctrl-l, Right", description: "Move to right split", command: "jump_view_right", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "q, Ctrl-q", description: "Close current window", command: "wclose", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "o, Ctrl-o", description: "Close all other windows", command: "wonly", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "H", description: "Swap window left", command: "swap_view_left", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "J", description: "Swap window down", command: "swap_view_down", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "K", description: "Swap window up", command: "swap_view_up", mode: Mode::Window, category: Category::Window },
        Keybinding { key: "L", description: "Swap window right", command: "swap_view_right", mode: Mode::Window, category: Category::Window },

        // Space Mode
        Keybinding { key: "f", description: "Open file picker (project root)", command: "file_picker", mode: Mode::Space, category: Category::Navigation },
        Keybinding { key: "F", description: "Open file picker (cwd)", command: "file_picker_in_current_directory", mode: Mode::Space, category: Category::Navigation },
        Keybinding { key: "b", description: "Open buffer picker", command: "buffer_picker", mode: Mode::Space, category: Category::Buffer },
        Keybinding { key: "j", description: "Open jumplist picker", command: "jumplist_picker", mode: Mode::Space, category: Category::Navigation },
        Keybinding { key: "g", description: "Open changed file picker", command: "changed_file_picker", mode: Mode::Space, category: Category::Navigation },
        Keybinding { key: "k", description: "Show hover documentation (LSP)", command: "hover", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "s", description: "Open document symbol picker", command: "lsp_or_syntax_symbol_picker", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "S", description: "Open workspace symbol picker", command: "lsp_or_syntax_workspace_symbol_picker", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "d", description: "Open diagnostics picker", command: "diagnostics_picker", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "D", description: "Open workspace diagnostics", command: "workspace_diagnostics_picker", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "r", description: "Rename symbol (LSP)", command: "rename_symbol", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "a", description: "Apply code action (LSP)", command: "code_action", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "h", description: "Select references to symbol", command: "select_references_to_symbol_under_cursor", mode: Mode::Space, category: Category::Lsp },
        Keybinding { key: "'", description: "Open last fuzzy picker", command: "last_picker", mode: Mode::Space, category: Category::Navigation },
        Keybinding { key: "w", description: "Enter window mode", command: "N/A", mode: Mode::Space, category: Category::Window },
        Keybinding { key: "c", description: "Toggle line comment", command: "toggle_comments", mode: Mode::Space, category: Category::Editing },
        Keybinding { key: "C", description: "Toggle block comment", command: "toggle_block_comments", mode: Mode::Space, category: Category::Editing },
        Keybinding { key: "Alt-c", description: "Toggle line comment (alt)", command: "toggle_line_comments", mode: Mode::Space, category: Category::Editing },
        Keybinding { key: "p", description: "Paste from system clipboard", command: "paste_clipboard_after", mode: Mode::Space, category: Category::Clipboard },
        Keybinding { key: "P", description: "Paste before from clipboard", command: "paste_clipboard_before", mode: Mode::Space, category: Category::Clipboard },
        Keybinding { key: "y", description: "Yank to system clipboard", command: "yank_to_clipboard", mode: Mode::Space, category: Category::Clipboard },
        Keybinding { key: "Y", description: "Yank main sel to clipboard", command: "yank_main_selection_to_clipboard", mode: Mode::Space, category: Category::Clipboard },
        Keybinding { key: "R", description: "Replace from clipboard", command: "replace_selections_with_clipboard", mode: Mode::Space, category: Category::Clipboard },
        Keybinding { key: "/", description: "Global search in project", command: "global_search", mode: Mode::Space, category: Category::Search },
        Keybinding { key: "?", description: "Open command palette", command: "command_palette", mode: Mode::Space, category: Category::Other },

        // Unimpaired
        Keybinding { key: "]d", description: "Go to next diagnostic", command: "goto_next_diag", mode: Mode::Unimpaired, category: Category::Lsp },
        Keybinding { key: "[d", description: "Go to previous diagnostic", command: "goto_prev_diag", mode: Mode::Unimpaired, category: Category::Lsp },
        Keybinding { key: "]D", description: "Go to last diagnostic", command: "goto_last_diag", mode: Mode::Unimpaired, category: Category::Lsp },
        Keybinding { key: "[D", description: "Go to first diagnostic", command: "goto_first_diag", mode: Mode::Unimpaired, category: Category::Lsp },
        Keybinding { key: "]f", description: "Go to next function", command: "goto_next_function", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "[f", description: "Go to previous function", command: "goto_prev_function", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "]t", description: "Go to next type definition", command: "goto_next_class", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "[t", description: "Go to previous type def", command: "goto_prev_class", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "]a", description: "Go to next argument/param", command: "goto_next_parameter", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "[a", description: "Go to previous argument", command: "goto_prev_parameter", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "]c", description: "Go to next comment", command: "goto_next_comment", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "[c", description: "Go to previous comment", command: "goto_prev_comment", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "]T", description: "Go to next test", command: "goto_next_test", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "[T", description: "Go to previous test", command: "goto_prev_test", mode: Mode::Unimpaired, category: Category::TreeSitter },
        Keybinding { key: "]p", description: "Go to next paragraph", command: "goto_next_paragraph", mode: Mode::Unimpaired, category: Category::Navigation },
        Keybinding { key: "[p", description: "Go to previous paragraph", command: "goto_prev_paragraph", mode: Mode::Unimpaired, category: Category::Navigation },
        Keybinding { key: "]g", description: "Go to next git change", command: "goto_next_change", mode: Mode::Unimpaired, category: Category::Navigation },
        Keybinding { key: "[g", description: "Go to previous git change", command: "goto_prev_change", mode: Mode::Unimpaired, category: Category::Navigation },
        Keybinding { key: "]G", description: "Go to last git change", command: "goto_last_change", mode: Mode::Unimpaired, category: Category::Navigation },
        Keybinding { key: "[G", description: "Go to first git change", command: "goto_first_change", mode: Mode::Unimpaired, category: Category::Navigation },
        Keybinding { key: "]Space", description: "Add newline below", command: "add_newline_below", mode: Mode::Unimpaired, category: Category::Editing },
        Keybinding { key: "[Space", description: "Add newline above", command: "add_newline_above", mode: Mode::Unimpaired, category: Category::Editing },

        // Insert Mode
        Keybinding { key: "Escape", description: "Return to normal mode", command: "normal_mode", mode: Mode::Insert, category: Category::Other },
        Keybinding { key: "Ctrl-s", description: "Commit undo checkpoint", command: "commit_undo_checkpoint", mode: Mode::Insert, category: Category::Other },
        Keybinding { key: "Ctrl-x", description: "Trigger autocomplete", command: "completion", mode: Mode::Insert, category: Category::Lsp },
        Keybinding { key: "Ctrl-r", description: "Insert from register", command: "insert_register", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Ctrl-w, Alt-Backspace", description: "Delete word backward", command: "delete_word_backward", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Alt-d, Alt-Delete", description: "Delete word forward", command: "delete_word_forward", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Ctrl-u", description: "Delete to line start", command: "kill_to_line_start", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Ctrl-k", description: "Delete to line end", command: "kill_to_line_end", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Ctrl-h, Backspace", description: "Delete char backward", command: "delete_char_backward", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Ctrl-d, Delete", description: "Delete char forward", command: "delete_char_forward", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Ctrl-j, Enter", description: "Insert newline", command: "insert_newline", mode: Mode::Insert, category: Category::Editing },
        Keybinding { key: "Up", description: "Move line up", command: "move_line_up", mode: Mode::Insert, category: Category::Movement },
        Keybinding { key: "Down", description: "Move line down", command: "move_line_down", mode: Mode::Insert, category: Category::Movement },
        Keybinding { key: "Left", description: "Move char left", command: "move_char_left", mode: Mode::Insert, category: Category::Movement },
        Keybinding { key: "Right", description: "Move char right", command: "move_char_right", mode: Mode::Insert, category: Category::Movement },
        Keybinding { key: "Home", description: "Go to line start", command: "goto_line_start", mode: Mode::Insert, category: Category::Movement },
        Keybinding { key: "End", description: "Go to line end", command: "goto_line_end_newline", mode: Mode::Insert, category: Category::Movement },

        // Picker
        Keybinding { key: "Tab, Down, Ctrl-n", description: "Next entry", command: "N/A", mode: Mode::Picker, category: Category::Navigation },
        Keybinding { key: "Shift-Tab, Up, Ctrl-p", description: "Previous entry", command: "N/A", mode: Mode::Picker, category: Category::Navigation },
        Keybinding { key: "PageUp, Ctrl-u", description: "Page up", command: "N/A", mode: Mode::Picker, category: Category::Navigation },
        Keybinding { key: "PageDown, Ctrl-d", description: "Page down", command: "N/A", mode: Mode::Picker, category: Category::Navigation },
        Keybinding { key: "Home", description: "Go to first entry", command: "N/A", mode: Mode::Picker, category: Category::Navigation },
        Keybinding { key: "End", description: "Go to last entry", command: "N/A", mode: Mode::Picker, category: Category::Navigation },
        Keybinding { key: "Enter", description: "Open selected", command: "N/A", mode: Mode::Picker, category: Category::Other },
        Keybinding { key: "Alt-Enter", description: "Open in background", command: "N/A", mode: Mode::Picker, category: Category::Other },
        Keybinding { key: "Ctrl-s", description: "Open horizontal split", command: "N/A", mode: Mode::Picker, category: Category::Window },
        Keybinding { key: "Ctrl-v", description: "Open vertical split", command: "N/A", mode: Mode::Picker, category: Category::Window },
        Keybinding { key: "Ctrl-t", description: "Toggle preview", command: "N/A", mode: Mode::Picker, category: Category::Other },
        Keybinding { key: "Escape, Ctrl-c", description: "Close picker", command: "N/A", mode: Mode::Picker, category: Category::Other },

        // Prompt
        Keybinding { key: "Escape, Ctrl-c", description: "Close prompt", command: "N/A", mode: Mode::Prompt, category: Category::Other },
        Keybinding { key: "Alt-b, Ctrl-Left", description: "Move word backward", command: "N/A", mode: Mode::Prompt, category: Category::Movement },
        Keybinding { key: "Alt-f, Ctrl-Right", description: "Move word forward", command: "N/A", mode: Mode::Prompt, category: Category::Movement },
        Keybinding { key: "Ctrl-b, Left", description: "Move char backward", command: "N/A", mode: Mode::Prompt, category: Category::Movement },
        Keybinding { key: "Ctrl-f, Right", description: "Move char forward", command: "N/A", mode: Mode::Prompt, category: Category::Movement },
        Keybinding { key: "Ctrl-e, End", description: "Move to end", command: "N/A", mode: Mode::Prompt, category: Category::Movement },
        Keybinding { key: "Ctrl-a, Home", description: "Move to start", command: "N/A", mode: Mode::Prompt, category: Category::Movement },
        Keybinding { key: "Ctrl-w, Alt-Backspace", description: "Delete word backward", command: "N/A", mode: Mode::Prompt, category: Category::Editing },
        Keybinding { key: "Alt-d, Alt-Delete", description: "Delete word forward", command: "N/A", mode: Mode::Prompt, category: Category::Editing },
        Keybinding { key: "Ctrl-u", description: "Delete to line start", command: "N/A", mode: Mode::Prompt, category: Category::Editing },
        Keybinding { key: "Ctrl-k", description: "Delete to line end", command: "N/A", mode: Mode::Prompt, category: Category::Editing },
        Keybinding { key: "Ctrl-p, Up", description: "Previous history entry", command: "N/A", mode: Mode::Prompt, category: Category::Navigation },
        Keybinding { key: "Ctrl-n, Down", description: "Next history entry", command: "N/A", mode: Mode::Prompt, category: Category::Navigation },
        Keybinding { key: "Ctrl-r", description: "Insert from register", command: "N/A", mode: Mode::Prompt, category: Category::Editing },
        Keybinding { key: "Tab", description: "Next completion", command: "N/A", mode: Mode::Prompt, category: Category::Other },
        Keybinding { key: "Shift-Tab", description: "Previous completion", command: "N/A", mode: Mode::Prompt, category: Category::Other },
        Keybinding { key: "Enter", description: "Confirm/execute", command: "N/A", mode: Mode::Prompt, category: Category::Other },
    ]
}

pub fn get_commands() -> Vec<Command> {
    vec![
        // File Operations
        Command { name: "write", aliases: &["w"], description: "Write changes to disk" },
        Command { name: "write!", aliases: &["w!"], description: "Force write, creating subdirectories" },
        Command { name: "quit", aliases: &["q"], description: "Close current view" },
        Command { name: "quit!", aliases: &["q!"], description: "Force close, ignoring unsaved changes" },
        Command { name: "write-quit", aliases: &["wq"], description: "Write and close view" },
        Command { name: "write-quit!", aliases: &["wq!"], description: "Force write and close" },
        Command { name: "exit", aliases: &["x", "xit"], description: "Write if modified, then quit" },
        Command { name: "exit!", aliases: &["x!", "xit!"], description: "Force write and quit" },
        Command { name: "quit-all", aliases: &["qa"], description: "Close all views" },
        Command { name: "quit-all!", aliases: &["qa!"], description: "Force close all views" },
        Command { name: "write-all", aliases: &["wa"], description: "Write all buffers to disk" },
        Command { name: "write-all!", aliases: &["wa!"], description: "Force write all buffers" },
        Command { name: "write-quit-all", aliases: &["wqa", "xa"], description: "Write all and close all views" },
        Command { name: "write-quit-all!", aliases: &["wqa!", "xa!"], description: "Force write all and close" },
        Command { name: "open", aliases: &["o", "edit", "e"], description: "Open file in current view" },
        Command { name: "new", aliases: &["n"], description: "Create new scratch buffer" },
        Command { name: "read", aliases: &["r"], description: "Load file into buffer" },
        Command { name: "reload", aliases: &["rl"], description: "Discard changes and reload file" },
        Command { name: "reload-all", aliases: &["rla"], description: "Reload all documents" },
        Command { name: "update", aliases: &["u"], description: "Write only if modified" },
        Command { name: "move", aliases: &["mv"], description: "Move buffer and file to new path" },
        Command { name: "cquit", aliases: &["cq"], description: "Quit with exit code (default 1)" },
        Command { name: "cquit!", aliases: &["cq!"], description: "Force quit with exit code" },

        // Buffer Operations
        Command { name: "buffer-close", aliases: &["bc", "bclose"], description: "Close current buffer" },
        Command { name: "buffer-close!", aliases: &["bc!", "bclose!"], description: "Force close buffer" },
        Command { name: "buffer-close-others", aliases: &["bco", "bcloseother"], description: "Close all other buffers" },
        Command { name: "buffer-close-others!", aliases: &["bco!", "bcloseother!"], description: "Force close all other buffers" },
        Command { name: "buffer-close-all", aliases: &["bca", "bcloseall"], description: "Close all buffers" },
        Command { name: "buffer-close-all!", aliases: &["bca!", "bcloseall!"], description: "Force close all buffers" },
        Command { name: "buffer-next", aliases: &["bn", "bnext"], description: "Go to next buffer" },
        Command { name: "buffer-previous", aliases: &["bp", "bprev"], description: "Go to previous buffer" },
        Command { name: "write-buffer-close", aliases: &["wbc"], description: "Write and close buffer" },
        Command { name: "write-buffer-close!", aliases: &["wbc!"], description: "Force write and close buffer" },

        // Splits
        Command { name: "vsplit", aliases: &["vs"], description: "Open file in vertical split" },
        Command { name: "vsplit-new", aliases: &["vnew"], description: "New scratch buffer in vsplit" },
        Command { name: "hsplit", aliases: &["hs", "sp"], description: "Open file in horizontal split" },
        Command { name: "hsplit-new", aliases: &["hnew"], description: "New scratch buffer in hsplit" },

        // Navigation
        Command { name: "goto", aliases: &["g"], description: "Go to line number" },
        Command { name: "change-current-directory", aliases: &["cd"], description: "Change working directory" },
        Command { name: "show-directory", aliases: &["pwd"], description: "Show current directory" },

        // Editing
        Command { name: "format", aliases: &["fmt"], description: "Format file using LSP/formatter" },
        Command { name: "indent-style", aliases: &[], description: "Set indentation style" },
        Command { name: "line-ending", aliases: &[], description: "Set line ending (crlf/lf)" },
        Command { name: "reflow", aliases: &[], description: "Hard-wrap lines to given width" },
        Command { name: "sort", aliases: &[], description: "Sort ranges in selection" },
        Command { name: "earlier", aliases: &["ear"], description: "Jump back in edit history" },
        Command { name: "later", aliases: &["lat"], description: "Jump forward in edit history" },
        Command { name: "yank-join", aliases: &[], description: "Yank joined selections" },

        // Clipboard
        Command { name: "clipboard-yank", aliases: &[], description: "Yank to system clipboard" },
        Command { name: "clipboard-yank-join", aliases: &[], description: "Yank joined to clipboard" },
        Command { name: "clipboard-paste-after", aliases: &[], description: "Paste clipboard after" },
        Command { name: "clipboard-paste-before", aliases: &[], description: "Paste clipboard before" },
        Command { name: "clipboard-paste-replace", aliases: &[], description: "Replace with clipboard" },
        Command { name: "primary-clipboard-yank", aliases: &[], description: "Yank to primary clipboard" },
        Command { name: "primary-clipboard-yank-join", aliases: &[], description: "Yank joined to primary" },
        Command { name: "primary-clipboard-paste-after", aliases: &[], description: "Paste primary after" },
        Command { name: "primary-clipboard-paste-before", aliases: &[], description: "Paste primary before" },
        Command { name: "primary-clipboard-paste-replace", aliases: &[], description: "Replace with primary" },
        Command { name: "show-clipboard-provider", aliases: &[], description: "Show clipboard provider" },

        // Configuration
        Command { name: "theme", aliases: &[], description: "Change/show editor theme" },
        Command { name: "set-option", aliases: &["set"], description: "Set config option at runtime" },
        Command { name: "toggle-option", aliases: &["toggle"], description: "Toggle config option" },
        Command { name: "get-option", aliases: &["get"], description: "Get config option value" },
        Command { name: "config-reload", aliases: &[], description: "Reload user config" },
        Command { name: "config-open", aliases: &[], description: "Open user config.toml" },
        Command { name: "config-open-workspace", aliases: &[], description: "Open workspace config.toml" },
        Command { name: "set-language", aliases: &["lang"], description: "Set buffer language" },
        Command { name: "encoding", aliases: &[], description: "Set file encoding" },

        // LSP
        Command { name: "lsp-workspace-command", aliases: &[], description: "Open LSP workspace command picker" },
        Command { name: "lsp-restart", aliases: &[], description: "Restart language server(s)" },
        Command { name: "lsp-stop", aliases: &[], description: "Stop language server(s)" },

        // Tree-sitter
        Command { name: "tree-sitter-scopes", aliases: &[], description: "Display tree-sitter scopes" },
        Command { name: "tree-sitter-highlight-name", aliases: &[], description: "Show highlight scope name" },
        Command { name: "tree-sitter-subtree", aliases: &["ts-subtree"], description: "Display tree-sitter subtree" },
        Command { name: "tree-sitter-layers", aliases: &[], description: "Show injection layers" },

        // Debugging
        Command { name: "debug-start", aliases: &["dbg"], description: "Start debug session" },
        Command { name: "debug-remote", aliases: &["dbg-tcp"], description: "Connect to debug adapter" },
        Command { name: "debug-eval", aliases: &[], description: "Evaluate debug expression" },

        // Shell
        Command { name: "run-shell-command", aliases: &["sh", "!"], description: "Run shell command" },
        Command { name: "insert-output", aliases: &[], description: "Insert shell output before" },
        Command { name: "append-output", aliases: &[], description: "Append shell output after" },
        Command { name: "pipe", aliases: &["|"], description: "Pipe selection through shell" },
        Command { name: "pipe-to", aliases: &[], description: "Pipe to shell, ignore output" },

        // Misc
        Command { name: "tutor", aliases: &[], description: "Open the Helix tutorial" },
        Command { name: "character-info", aliases: &["char"], description: "Info about char under cursor" },
        Command { name: "log-open", aliases: &[], description: "Open helix log file" },
        Command { name: "clear-register", aliases: &[], description: "Clear register(s)" },
        Command { name: "redraw", aliases: &[], description: "Re-render the UI" },
        Command { name: "yank-diagnostic", aliases: &[], description: "Yank diagnostic to register" },
        Command { name: "reset-diff-change", aliases: &["diffget", "diffg"], description: "Reset diff change at cursor" },
        Command { name: "echo", aliases: &[], description: "Print to statusline" },
        Command { name: "noop", aliases: &[], description: "Does nothing" },
    ]
}
